---
apiVersion: vra.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-vra-config-allianz-dev
spec:
  baseUrl: 'de.api.mgmt.cloud.vmware.com'
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-vra-secret-allianz-dev
      key: credentials
